name: "Download tracked files"

on:
  schedule:
    - cron: "0 17 * * *" # Every day at 17:00 UTC (12:00 EST)
  workflow_dispatch:

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: node
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - id: run-script
        name: Run download script
        run: |
          node index.js
      - id: add-and-commit
        name: Add and commit
        run: |
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Latest data"
      - id: push
        name: Push
        run: |
          git push